from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
import math
import random
from statistics import NormalDist, mean, stdev
from typing import Mapping, Sequence

from .resampling import circular_block_sample


_NORMAL = NormalDist()
_EULER_GAMMA = 0.5772156649015329


def _sample_skewness(values: Sequence[float]) -> float:
    n = len(values)
    if n < 3:
        return 0.0
    m = mean(values)
    s = stdev(values)
    if s == 0:
        return 0.0
    return (n / ((n - 1) * (n - 2))) * sum(((x - m) / s) ** 3 for x in values)


def _sample_kurtosis_pearson(values: Sequence[float]) -> float:
    n = len(values)
    if n < 4:
        return 3.0
    m = mean(values)
    s = stdev(values)
    if s == 0:
        return 3.0
    z4 = sum(((x - m) / s) ** 4 for x in values)
    excess = (
        (n * (n + 1) / ((n - 1) * (n - 2) * (n - 3))) * z4
        - (3 * (n - 1) ** 2 / ((n - 2) * (n - 3)))
    )
    return excess + 3.0


def sharpe_ratio(values: Sequence[float], *, periods_per_year: float = 1.0) -> float:
    if len(values) < 2:
        raise ValueError("at least two returns are required")
    if periods_per_year <= 0:
        raise ValueError("periods_per_year must be positive")
    sigma = stdev(values)
    if sigma == 0:
        if mean(values) > 0:
            return math.inf
        if mean(values) < 0:
            return -math.inf
        return 0.0
    return mean(values) / sigma * math.sqrt(periods_per_year)


@dataclass(frozen=True, slots=True)
class DeflatedSharpeResult:
    probability: float
    observed_sharpe: float
    benchmark_sharpe: float
    standard_error: float
    trials: int
    observations: int


def deflated_sharpe_ratio(values: Sequence[float], *, trials: int) -> DeflatedSharpeResult:
    """Approximate Deflated Sharpe Ratio probability.

    Sharpe is evaluated in native observation units. The benchmark is the
    expected maximum Sharpe generated by ``trials`` independent selections under
    the null, adjusted for observed skew and kurtosis through the Sharpe standard
    error. This intentionally avoids annualisation ambiguity inside the test.
    """

    n = len(values)
    if n < 3:
        raise ValueError("at least three observations are required")
    if trials <= 0:
        raise ValueError("trials must be positive")
    sigma = stdev(values)
    if sigma == 0:
        raise ValueError("deflated Sharpe is undefined for zero-variance returns")

    sr = mean(values) / sigma
    skew = _sample_skewness(values)
    kurtosis = _sample_kurtosis_pearson(values)
    variance_term = 1 - skew * sr + ((kurtosis - 1) / 4.0) * sr * sr
    variance_term = max(variance_term, 1e-12)
    standard_error = math.sqrt(variance_term / (n - 1))

    if trials == 1:
        benchmark = 0.0
    else:
        z1 = _NORMAL.inv_cdf(1 - 1 / trials)
        z2 = _NORMAL.inv_cdf(1 - 1 / (trials * math.e))
        benchmark = standard_error * ((1 - _EULER_GAMMA) * z1 + _EULER_GAMMA * z2)

    probability = _NORMAL.cdf((sr - benchmark) / standard_error)
    return DeflatedSharpeResult(
        probability=probability,
        observed_sharpe=sr,
        benchmark_sharpe=benchmark,
        standard_error=standard_error,
        trials=trials,
        observations=n,
    )


@dataclass(frozen=True, slots=True)
class PBOResult:
    probability_of_backtest_overfitting: float
    logits: tuple[float, ...]
    combinations_evaluated: int


def _slice_bounds(n_rows: int, n_slices: int) -> list[tuple[int, int]]:
    base, remainder = divmod(n_rows, n_slices)
    bounds = []
    cursor = 0
    for i in range(n_slices):
        width = base + (1 if i < remainder else 0)
        bounds.append((cursor, cursor + width))
        cursor += width
    return bounds


def _column_sharpes(matrix: Sequence[Sequence[float]], rows: Sequence[int]) -> list[float]:
    n_cols = len(matrix[0])
    scores: list[float] = []
    for col in range(n_cols):
        values = [float(matrix[row][col]) for row in rows]
        if len(values) < 2:
            scores.append(float("-inf"))
            continue
        sigma = stdev(values)
        if sigma == 0:
            scores.append(math.inf if mean(values) > 0 else (-math.inf if mean(values) < 0 else 0.0))
        else:
            scores.append(mean(values) / sigma)
    return scores


def probability_of_backtest_overfitting(
    returns_matrix: Sequence[Sequence[float]],
    *,
    n_slices: int = 8,
) -> PBOResult:
    """Combinatorially symmetric cross-validation estimate of PBO.

    Rows are chronological periods and columns are candidate configurations.
    OOS rank is defined from worst=1 to best=N. A selected IS winner whose OOS
    rank is at or below the median contributes to the estimated overfit rate.
    """

    if n_slices < 4 or n_slices % 2:
        raise ValueError("n_slices must be even and at least 4")
    n_rows = len(returns_matrix)
    if n_rows < n_slices:
        raise ValueError("not enough rows for requested slices")
    if not returns_matrix or not returns_matrix[0]:
        raise ValueError("returns matrix cannot be empty")
    n_cols = len(returns_matrix[0])
    if n_cols < 2:
        raise ValueError("PBO requires at least two candidate configurations")
    if any(len(row) != n_cols for row in returns_matrix):
        raise ValueError("returns matrix must be rectangular")

    bounds = _slice_bounds(n_rows, n_slices)
    slice_ids = tuple(range(n_slices))
    half = n_slices // 2
    logits: list[float] = []
    for train_slices in combinations(slice_ids, half):
        # Symmetric complements are both useful and deterministic; evaluating all
        # combinations is the canonical CSCV enumeration.
        train_set = set(train_slices)
        train_rows = [r for s in train_slices for r in range(*bounds[s])]
        test_rows = [r for s in slice_ids if s not in train_set for r in range(*bounds[s])]
        train_scores = _column_sharpes(returns_matrix, train_rows)
        selected = max(range(n_cols), key=lambda idx: (train_scores[idx], -idx))
        test_scores = _column_sharpes(returns_matrix, test_rows)
        selected_score = test_scores[selected]
        rank = 1 + sum(score < selected_score for score in test_scores)
        omega = rank / (n_cols + 1)
        logits.append(math.log(omega / (1 - omega)))

    pbo = sum(value <= 0 for value in logits) / len(logits)
    return PBOResult(pbo, tuple(logits), len(logits))


@dataclass(frozen=True, slots=True)
class RealityCheckResult:
    p_value: float
    observed_best_mean: float
    bootstrap_samples: int


def reality_check(
    returns_by_candidate: Mapping[str, Sequence[float]],
    *,
    bootstrap_samples: int = 2000,
    seed: int = 0,
    block_size: int = 1,
) -> RealityCheckResult:
    """White-style max-mean bootstrap reality check against a zero benchmark.

    Candidate series are centered under the null and resampled using common row
    indices, preserving contemporaneous cross-candidate dependence.
    """

    if len(returns_by_candidate) < 2:
        raise ValueError("reality check requires at least two candidates")
    if bootstrap_samples <= 0 or block_size <= 0:
        raise ValueError("bootstrap_samples and block_size must be positive")
    names = tuple(sorted(returns_by_candidate))
    n = len(returns_by_candidate[names[0]])
    if n < 2 or any(len(returns_by_candidate[name]) != n for name in names):
        raise ValueError("candidate return series must have equal length >= 2")

    observed = max(mean(returns_by_candidate[name]) for name in names)
    if observed <= 0:
        return RealityCheckResult(1.0, observed, bootstrap_samples)

    centered = {
        name: [float(x) - mean(returns_by_candidate[name]) for x in returns_by_candidate[name]]
        for name in names
    }
    rng = random.Random(seed)
    exceedances = 0
    row_ids = list(range(n))
    for _ in range(bootstrap_samples):
        sampled_ids = [int(x) for x in circular_block_sample(row_ids, rng, block_size)]
        statistic = max(mean([centered[name][i] for i in sampled_ids]) for name in names)
        if statistic >= observed:
            exceedances += 1
    p_value = (exceedances + 1) / (bootstrap_samples + 1)
    return RealityCheckResult(p_value, observed, bootstrap_samples)


def holm_bonferroni(p_values: Mapping[str, float], *, alpha: float = 0.05) -> dict[str, bool]:
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1")
    if not p_values:
        raise ValueError("p_values cannot be empty")
    for value in p_values.values():
        if not 0 <= value <= 1:
            raise ValueError("p-values must lie in [0, 1]")

    ordered = sorted(p_values.items(), key=lambda item: (item[1], item[0]))
    decisions = {name: False for name in p_values}
    for rank, (name, value) in enumerate(ordered, start=1):
        threshold = alpha / (len(ordered) - rank + 1)
        if value <= threshold:
            decisions[name] = True
        else:
            break
    return decisions
