'use strict';
const savedSnapshot = document.getElementById('saved-snapshot') ? JSON.parse(document.getElementById('saved-snapshot').textContent) : null;
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '—').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles = {overview:['System overview','Overview','◫'],data:['Markets & data','Markets & data','◇'],research:['Research laboratory','Research','α'],strategies:['Strategy registry','Strategies','≋'],runtime:['PAPER / SHADOW runtime','Runtime','⇄'],risk:['Risk & reconciliation','Risk','△'],jobs:['Jobs & activity','Jobs & activity','⌁'],evidence:['Evidence & diagnostics','Evidence','⊞']};
let state=null, page='overview', fetching=false, connection='Connecting', lastReceived=null, currentDrawer=null, renderedSignature=null;
const signature=p=>JSON.stringify({...p,meta:{...p.meta,generated_at:null}});
const view={mode:'paper',chart:'market',venue:'BINANCE_USDM',range:'all',search:{},filter:{},sort:{},point:0};
const investigations=new Map();
function register(id,title,body){investigations.set(id,{title,body});return id;}
const number=(v,d=2)=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-GB',{maximumFractionDigits:d});
const stamp=v=>v?new Date(v).toISOString().replace('T',' ').replace('.000Z',' UTC').replace('Z',' UTC'):'Not recorded';
const shortTime=v=>v?new Date(v).toISOString().slice(11,23):'—';
const friendly=v=>String(v??'Unavailable').replaceAll('_',' ').toLowerCase().replace(/^./,s=>s.toUpperCase());
const tone=v=>/CRITICAL|HALTED|FAIL|BREACH|MISMATCH/.test(v)?'critical':/BLOCK|STALE|UNKNOWN|UNAVAILABLE|WAIT|NOT_|ARCHIVAL|WARNING|EXPIRED/.test(v)?'warning':/VERIFIED|RECENT|PASS|ACTIVE|CONTINUE/.test(v)?'good':'cyan';
const tag=(v,t)=>`<span class="tag ${t||tone(v)}">${esc(friendly(v))}</span>`;
const inspect=(id,label='Inspect →')=>`<button class="link-button" data-inspect="${esc(id)}">${esc(label)}</button>`;
const panel=(kicker,title,body,extra='',foot='')=>`<article class="panel"><div class="panel-head"><div><div class="eyebrow">${esc(kicker)}</div><h2>${esc(title)}</h2></div>${extra}</div>${body}${foot?`<div class="panel-foot">${foot}</div>`:''}</article>`;
const empty=(title,detail,id)=>`<div class="empty"><div class="empty-symbol">∅</div><strong>${esc(title)}</strong><p>${esc(detail)}</p>${id?inspect(id,'Inspect source requirements →'):''}</div>`;
const json=v=>`<pre>${esc(JSON.stringify(v,null,2))}</pre>`;
const kv=obj=>`<dl class="kv">${Object.entries(obj).map(([k,v])=>`<dt>${esc(friendly(k))}</dt><dd>${esc(typeof v==='object'?JSON.stringify(v):v)}</dd>`).join('')}</dl>`;
const intro=txt=>`<div class="note">${esc(txt)}</div>`;
function metric(label,value,detail,id){return `<button class="metric" data-inspect="${esc(id)}"><span class="metric-label">${esc(label)} ↗</span><strong class="metric-value">${esc(value)}</strong><small>${esc(detail)}</small></button>`;}
function setupInvestigations(){
 investigations.clear();
 const p=state.execution.paper||{};
 register('performance','Performance & valuation',intro(state.performance.reason)+kv({source:state.execution.source,window:'No equity history supplied',currency:'Not persisted; no currency assumed',valuation_time:p.valuation_at||'Unavailable',cost_treatment:p.cost_basis||'Unavailable'})+json(state.performance));
 register('cash','PAPER ledger cash',intro('Cash is the persisted ledger balance. It excludes the current marked value of open positions and must not be labelled equity.')+kv({source:state.execution.source,runtime_id:p.runtime_id,checkpoint_at:p.valuation_at,currency:'Not persisted',cash:p.cash})+json(p));
 register('pnl','Realised position P&L',intro(p.cost_basis||'No connected PAPER checkpoint.')+kv({value:p.realized_pnl,commissions:p.commissions,financing_costs:p.financing_costs,period:'Cumulative positions in the selected checkpoint; not a daily return',currency:'Not persisted',source:state.execution.source}));
 register('exposure','Exposure & position valuation',intro('Gross/net exposure and unrealised P&L require current market marks. Average entry price is not a current mark.')+json({positions:p.positions||[],marks_persisted:p.marks_persisted??false,source:state.execution.source}));
 register('runtime-source','Runtime connection',intro('Start the local observer with --runtime-db /absolute/path/to/runtime.db. The existing F5.6 database is opened mode=ro and query_only. No database, runtime lease or order is created.')+kv({source:state.execution.source,connected:state.meta.runtime_connected,refresh:'15 seconds; non-overlapping; 8 second browser timeout',read_budget:'64 runtimes / 10,000 verified events per runtime / 1 second SQL budget',on_limit:'Status unavailable; dedicated summary service required',scheduler:'No scheduler/agent feed connected'})+json(state.execution));
 register('risk-source','Risk authority & observability',intro('The observer does not read or modify a global kill switch or live authority. Current limit utilisation is not persisted by this runtime contract. Unknown is not clear.')+json(state.risk));
 register('campaigns','Alpha-v1 progression',intro('Campaigns are frozen preregistration contracts from this saved package. No current remote binding report, trial results, OOS performance or winner selection is connected.')+json({gates:state.gates,campaigns:state.campaigns}));
 register('strategies','Strategy registry availability',intro(state.strategies.message)+json(state.strategies));
 register('data-source','Market source & audit scope',intro('These immutable acceptance-slice partitions were loaded from the package. SHA-256 and row counts are verified on each response. Gap, duplicate and exchange-sequence audits are unavailable. Reported raw lineage is historical evidence, not a fresh raw-file audit.')+kv({state:state.market.state,dataset_id:state.market.manifest.dataset_id,first_source_event:state.market.manifest.start_time,decision_time:state.market.manifest.decision_time,last_ingestion:'Not connected',error:state.market.error}));
 register('jobs-source','Jobs & worker telemetry',intro('The runtime store exposes persisted runtime IDs, creation times, heartbeats, leases, events and checkpoints. Creation time is not current-task start time. Worker task assignments, elapsed task duration, schedules and completion estimates are unavailable.')+json(state.jobs));
 register('diagnostics','Observer diagnostics',kv({connection,last_response:lastReceived,generated_at:state.meta.generated_at,environment:state.meta.environment,source:state.meta.source,schema:state.schema_version,fixtures:state.meta.fixtures,execution_authority:'None; all mutation methods rejected',upstream_freshness:'Persisted source time, never browser refresh time'})+json(state.meta));
 Object.entries(state.market.records).forEach(([id,record])=>register(id,id,intro(record.classification||'Packaged archival evidence. Source timestamps remain unchanged on refresh.')+kv({source:record.path,sha256:record.sha256||'Not supplied'})+json(record.content)));
 state.gates.forEach(g=>register(g.id,`${g.id} · ${g.name}`,intro(g.detail)+json(g)));
 state.alerts.forEach((a,i)=>register('alert-'+i,a.title,intro(a.detail)+kv({severity:a.severity,code:a.code,workspace:titles[a.target]?.[1]})+`<div class="drawer-section"><button data-go="${esc(a.target)}">Open ${esc(titles[a.target]?.[1])} →</button></div>`+(a.record&&investigations.has(a.record)?inspect(a.record,'Open supporting evidence →'):'')));
}
function healthMetrics(){const p=state.execution.paper||{};return `<div class="metrics">${metric('System state',friendly(state.health),'Inspect prioritised exceptions','alert-0')}${metric('PAPER equity','—','Current market marks unavailable','performance')}${metric('PAPER cash',number(p.cash),'Ledger units · currency not persisted','cash')}${metric('Realised P&L',number(p.realized_pnl),'Cumulative · before separate costs','pnl')}${metric('Gross / net exposure','—','Current market marks unavailable','exposure')}${metric('Risk limits','Unknown','Current utilisation not persisted','risk-source')}</div>`;}
function table(id,columns,rows,{search=false,filter=null}={}){
 let list=rows;
 const query=(view.search[id]||'').toLowerCase();
 if(query)list=list.filter(r=>JSON.stringify(r).toLowerCase().includes(query));
 if(filter&&view.filter[id])list=list.filter(r=>String(r[filter.key])===view.filter[id]);
 const sort=view.sort[id];
 if(sort)list=[...list].sort((a,b)=>{const x=a[sort.key],y=b[sort.key];return (typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??'')))*sort.dir;});
 const toolbar=search||filter?`<div class="table-toolbar">${search?`<input data-search="${id}" aria-label="Search ${id}" value="${esc(view.search[id]||'')}" placeholder="Search this table…">`:''}${filter?`<select data-filter="${id}" aria-label="Filter ${id}"><option value="">All ${esc(filter.label)}</option>${[...new Set(rows.map(r=>r[filter.key]))].map(v=>`<option ${view.filter[id]===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`:''}<small>${list.length} of ${rows.length} records</small></div>`:'';
 return `${toolbar}<div class="table-wrap"><table><thead><tr>${columns.map(([key,label])=>`<th aria-sort="${sort?.key===key?(sort.dir===1?'ascending':'descending'):'none'}"><button data-sort="${id}" data-key="${key}">${esc(label)} ${sort?.key===key?(sort.dir===1?'↑':'↓'):'↕'}</button></th>`).join('')}</tr></thead><tbody>${list.slice(0,200).map(r=>`<tr>${columns.map(([key,,render])=>`<td>${render?render(r):esc(r[key])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length}">No matching records.</td></tr>`}</tbody></table></div>${list.length>200?intro('Showing the first 200 matching rows. Narrow the search to inspect further.'):''}`;
}
function chart(){
 const controls=`<div class="chart-controls"><select id="chart-type" aria-label="Chart metric"><option value="market" ${view.chart==='market'?'selected':''}>Captured market prices</option><option value="performance" ${view.chart==='performance'?'selected':''}>PAPER performance</option></select>${view.chart==='market'?`<select id="chart-venue" aria-label="Chart venue">${[...new Set(state.market.trades.map(t=>t.venue))].map(v=>`<option ${v===view.venue?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="chart-range" aria-label="Chart range"><option value="all" ${view.range==='all'?'selected':''}>Full capture</option><option value="last5" ${view.range==='last5'?'selected':''}>Last 5 trades</option></select><span class="chart-legend">● BTC perpetual / USDT</span>`:''}</div>`;
 if(view.chart==='performance')return controls+empty('Equity history unavailable',state.performance.reason,'performance');
 let rows=state.market.trades.filter(t=>t.venue===view.venue);if(view.range==='last5')rows=rows.slice(-5);
 if(!rows.length)return controls+empty('No trade observations','No verified trade partition is available.','data-source');
 const values=rows.map(r=>Number(r.price)),lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.3,.05),min=lo-pad,max=hi+pad;
 const t0=Date.parse(rows[0].time),t1=Date.parse(rows.at(-1).time);
 const cw=window.innerWidth<=540?Math.max(280,window.innerWidth-70):810,left=cw<500?12:55,right=cw-75;
 const x=r=>left+(Date.parse(r.time)-t0)/Math.max(t1-t0,1)*(right-left),y=v=>178-(v-min)/(max-min)*145;
 const points=rows.map(r=>`${x(r)},${y(Number(r.price))}`).join(' ');
 const index=Math.min(view.point,rows.length-1),selected=rows[index];
 register('chart-point','Captured trade · '+selected.trade_id,intro('Observed historical market price. This is neither a simulated fill nor portfolio performance.')+json(selected)+inspect(selected.evidence_id,'Open source partition →'));
 return controls+`<div class="chart-wrap"><svg class="chart" viewBox="0 0 ${cw} 215" role="img" aria-label="${esc(rows.length+' archived trades on '+view.venue+' from '+stamp(rows[0].time)+' to '+stamp(rows.at(-1).time)+'. Prices '+min.toFixed(2)+' to '+max.toFixed(2)+' USDT.')}" preserveAspectRatio="none">${[0,.25,.5,.75,1].map(t=>{const value=min+(max-min)*t,yy=y(value);return `<line class="gridline" x1="${left}" y1="${yy}" x2="${right}" y2="${yy}"/><text x="${right+8}" y="${yy+4}">${value.toFixed(2)}</text>`;}).join('')}<polyline points="${points}" fill="none" stroke="#69c7e8" stroke-width="2" vector-effect="non-scaling-stroke"/>${rows.map((r,i)=>`<circle cx="${x(r)}" cy="${y(Number(r.price))}" r="${i===index?4:2}" fill="${i===index?'#e3eaf2':'#69c7e8'}"/>`).join('')}<text x="${left}" y="205">${shortTime(rows[0].time)}</text><text x="${right-85}" y="205">${shortTime(rows.at(-1).time)}</text></svg></div><div class="range-label"><span>Inspect trade</span><input class="chart-range" id="chart-point" type="range" min="0" max="${rows.length-1}" value="${index}" aria-label="Inspect captured trade"><span>${index+1}/${rows.length}</span></div><div class="chart-inspect">${esc(shortTime(selected.time))} UTC · ${number(selected.price)} USDT · ${number(selected.quantity,5)} BTC ${inspect('chart-point','Evidence ↗')}</div>`;
}
function chartPanel(){return panel('ANALYTICAL WORKSPACE',view.chart==='market'?'Market context':'PAPER performance',chart(),tag(view.chart==='market'?'ARCHIVAL':'UNAVAILABLE','warning'),`<span>22 SEP 2026 · SOURCE TIME / UTC · ${view.chart==='market'?'OBSERVED PRICES':'NO VALUATION SERIES'}</span>${inspect('data-source','Source ↗')}`);}
function exceptions(limit=10){return `<div class="exceptions">${state.alerts.slice(0,limit).map((a,i)=>`<button class="exception ${a.severity.toLowerCase()}" data-inspect="alert-${i}"><code>${esc(a.severity)} / ${esc(a.code)}</code><div class="exception-head"><strong>${esc(a.title)}</strong><span>↗</span></div><p>${esc(a.detail)}</p></button>`).join('')}</div>`;}
function flow(){return panel('SYSTEM MAP','From evidence to observation',`<div class="flow">${[['01','Market data','Archival slice','data-source'],['02','Research','6 contracts','campaigns'],['03','Validation','Binding blocked','campaigns'],['04','Risk','Limits unknown','risk-source'],['05','Runtime',state.meta.runtime_connected?'Persisted state':'Disconnected','runtime-source']].map(([n,name,s,id])=>`<button class="flow-node" data-inspect="${id}"><span class="num">${n}</span><strong>${name}</strong><small>${s}</small></button>`).join('')}</div>`,tag('READ ONLY'),'<span>Dependency path · node labels show source availability, not worker activity</span>');}
function campaignTable(){return table('campaigns',[['campaign_id','Contract',r=>inspect(r.campaign_id,r.campaign_id)],['family','Research family',r=>friendly(r.family)],['stage','Stage',r=>tag(r.stage,'cyan')],['fold_status','Eligibility',r=>tag(r.fold_status,'warning')],['minimum_trades','Min. trades'],['minimum_samples','Min. samples']],state.campaigns,{search:true});}
function activity(){const events=state.execution.runtimes.flatMap(r=>(r.recent_events||[]).map(e=>({...e,runtime_id:r.runtime_id,mode:r.mode}))).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).slice(0,100);if(!events.length)return empty('No runtime activity connected','No events are invented from the packaged acceptance results.','jobs-source');return events.map((e,i)=>{const id='event-'+i;register(id,e.event_type,json(e)+inspect(e.runtime_id,'Inspect runtime →'));return `<div class="activity-row"><time>${esc(shortTime(e.occurred_at))}<br>UTC</time><button data-inspect="${id}">${esc(friendly(e.event_type))}<br><small>${esc(e.runtime_id)} · sequence ${e.sequence}</small></button>${tag(e.mode,'cyan')}</div>`;}).join('');}
function overview(){return healthMetrics()+`<div class="grid overview-main">${chartPanel()}${panel('PRIORITISED EXCEPTIONS','Needs attention',exceptions(3),tag(String(state.alerts.length)+' open','warning'),`<span>Ordered by consequence</span><button class="link-button" data-go="risk">View all →</button>`)}</div><div class="grid">${panel('RESEARCH → STRATEGIES','Strategy readiness',table('readiness',[['family','Preregistered family',r=>inspect(r.campaign_id,friendly(r.family))],['stage','Stage',r=>tag(r.stage,'cyan')],['fold_status','Blocker',r=>'History / folds / samples']],state.campaigns),`<button class="link-button" data-go="research">Research →</button>`,`<span>Contracts only · no empirical strategy ranking</span>`)}${panel('PAPER PORTFOLIO','Exposure & positions',exposure(),inspect('exposure','Source ↗'))}</div><div class="wide-panel">${flow()}</div>${panel('PERSISTED EVENTS','Runtime activity',activity(),`<button class="link-button" data-go="jobs">All activity →</button>`)}`;}
function exposure(){const positions=state.execution.paper?.positions||[];if(!positions.length)return empty('Exposure unavailable','Connect a PAPER checkpoint and a current valuation source to measure gross and net exposure.','exposure');return intro('Position quantities are persisted. Current marks, notional exposure and unrealised P&L are unavailable.')+table('exposure',[['symbol','Instrument'],['qty','Quantity',r=>number(r.qty,6)],['side','Side'],['mark','Mark',r=>'Unavailable']],positions);}
function dataPage(){const m=state.market.manifest;return `<div class="metrics">${metric('Source state','Archive','No live ingestion connected','data-source')}${metric('Events',number(m.event_count,0),'Captured-scope observations','dataset-manifest')}${metric('Partitions',number(m.partitions?.length,0),'Content hashes verified at read','dataset-manifest')}${metric('Raw captures',number(state.market.report.raw_capture_count,0),'Count from acceptance report','capture-report')}${metric('Venues',number(new Set(state.market.partitions.map(p=>p.venue)).size,0),'Captured venues, not active feeds','data-source')}${metric('Audit coverage','Partial','Gap / duplicate / sequence unavailable','data-source')}</div><div class="wide-panel">${panel('DATASET / '+(m.dataset_id||'UNAVAILABLE'),'Coverage & source lineage',intro('History shown below is the available capture interval. It does not establish continuous historical coverage. All timestamps are UTC. Last successful ongoing ingestion: unavailable.')+table('partitions',[['venue','Venue'],['kind','Data type'],['row_count','Rows'],['min_event_time','First event',r=>stamp(r.min_event_time)],['max_event_time','Last event',r=>stamp(r.max_event_time)],['integrity','Partition hash',r=>tag(r.integrity)],['gap_audit','Gaps'],['duplicate_audit','Duplicates'],['sequence_audit','Sequence'],['lineage_audit','Raw lineage'],['evidence_id','Evidence',r=>inspect(r.evidence_id)]],state.market.partitions,{search:true,filter:{key:'kind',label:'data types'}}),inspect('dataset-manifest','Manifest ↗'))}</div><div class="grid">${chartPanel()}${panel('AUDIT LIMITATIONS','What the slice can establish',`<div class="panel-body"><p class="audit-explainer">Partition bytes and row counts are verified. The acceptance report records complete raw lineage on the capture host.<br><br>A trade sample cannot establish that no trades are missing. A single order-book snapshot cannot prove sequence continuity or reconstruct an L2 update stream.<br><br>Long-horizon gap, duplicate and venue-sequence reports must be connected before the display can report those audits as passed.</p></div>`,tag('PARTIAL','warning'))}</div>`;}
function research(){return `<div class="wide-panel">${panel('ALPHA-V1 / FROZEN CONTRACTS','Research campaigns',intro('Preregistered hypotheses, not evaluated strategies. OOS returns, observed sample sizes, trading-cost results and robustness evidence are not connected. No winner or profitability claim.')+campaignTable(),tag('BINDING BLOCKED','warning'))}</div>${panel('A01–A28 / PACKAGED BASELINE','Validation gates',`<div class="gate-grid">${state.gates.map(g=>`<button class="gate" data-inspect="${g.id}"><strong>${g.id}</strong><small>${esc(g.name)}</small>${tag(g.state,g.state==='BOUNDARY_VERIFIED'?'cyan':'warning')}</button>`).join('')}</div>`,inspect('campaigns','Contract evidence ↗'))}`;}
function strategies(){return panel('CURRENT REGISTRY','Candidates & validated survivors',empty('Current strategy registry not connected',state.strategies.message,'strategies'),tag('UNAVAILABLE','warning'))+`<div class="subheading"><h2>Dependencies preventing progression</h2></div>${panel('RESEARCH CONTRACTS','Available preregistrations',campaignTable(),inspect('campaigns','Validation evidence ↗'))}`;}
function runtime(){const p=state.execution[view.mode]||{};let content=`<div class="runtime-tabs"><button data-mode="paper" aria-pressed="${view.mode==='paper'}">PAPER</button><button data-mode="shadow" aria-pressed="${view.mode==='shadow'}">SHADOW</button></div>`;if(!p.available)return content+panel(view.mode.toUpperCase()+' / READ ONLY','Runtime state',empty('No '+view.mode.toUpperCase()+' checkpoint available',p.message||'Supply a compatible F5.6 runtime database to inspect its persisted state.','runtime-source'),tag('UNAVAILABLE','warning'));
 content+=panel('PERSISTED CHECKPOINT',p.runtime_id,`<div class="panel-body">${kv({status:p.status,lease:p.lease_state,reconciliation:p.reconciliation,halt_reason:p.halt_reason||'Not recorded',checkpoint_at:p.valuation_at||'See runtime evidence',currency:'Not persisted'})}</div>`,inspect(p.runtime_id,'Inspect runtime ↗'));
 if(view.mode==='shadow')return content+`<div class="subheading"><h2>SHADOW decision accounting</h2></div>`+panel('SIMULATED DECISIONS','Submission invariant',`<div class="panel-body">${kv({decisions:p.decisions,sent_true_results:p.submitted_orders,invariant:p.zero_submit_invariant,gateway_submission_flag:p.venue_submission_state})}</div>`+intro('Zero persisted sent=true results do not establish the current gateway flag or authorise LIVE trading.'),tag(p.zero_submit_invariant));
 content+=`<div class="subheading"><h2>PAPER accounting</h2>${inspect('pnl','Definitions & costs ↗')}</div><div class="metrics">${metric('Cash',number(p.cash),'Ledger units','cash')}${metric('Realised P&L',number(p.realized_pnl),'Before separate costs','pnl')}${metric('Commissions',number(p.commissions),'Persisted ledger cost','pnl')}${metric('Financing',number(p.financing_costs),'Persisted ledger cost','pnl')}${metric('Equity','—','Marks unavailable','performance')}${metric('Unrealised P&L','—','Marks unavailable','exposure')}</div>`;
 for(const [key,label,cols] of [['positions','Positions',[['symbol','Instrument'],['side','Side'],['qty','Quantity'],['avg_price','Entry price'],['realized_pnl','Realised P&L'],['pnl','Unrealised P&L']]],['orders','Pending orders',[['id','Order ID'],['symbol','Instrument'],['side','Side'],['qty','Quantity'],['state','State']]],['fills','Simulated fills',[['order_id','Order ID'],['symbol','Instrument'],['price','Fill price'],['qty','Quantity'],['fee','Commission'],['slippage_bps','Slippage bps'],['timestamp','Source time']]]]){
 const rows=(p[key]||[]).map((row,i)=>{const id=`${key}-${i}`;register(id,label+' record',intro('Persisted PAPER simulation. Currency is not stored in this contract.')+json(row)+inspect(p.runtime_id,'Runtime evidence →'));return {...row,inspection:id};});
 content+=`<div class="wide-panel">${panel('PAPER / '+(p.valuation_at?stamp(p.valuation_at):'CHECKPOINT'),label,rows.length?table(key,[...cols,['inspection','Details',r=>inspect(r.inspection)]],rows,{search:true}):empty('No '+label.toLowerCase()+' in checkpoint','This empty collection comes from the connected persisted checkpoint.'),tag(rows.length+' records','cyan'))}</div>`;
 }return content;
}
function risk(){return `<div class="grid equal">${panel('AUTHORITATIVE STATUS','Runtime risk observations',`<div class="panel-body">${kv({state:state.risk.state||'UNKNOWN',degradation:state.risk.degradation_state||'UNKNOWN',global_kill_switch:'Not exposed by this contract',limit_utilisation:state.risk.limits_state||'UNAVAILABLE',live_authority:'Not granted by this interface'})}</div>`+table('risk-conditions',[['condition','Condition'],['state','Persisted state',r=>tag(r.state)]],state.risk.conditions||[]),inspect('risk-source','Source ↗'))}${panel('ALL EXCEPTIONS','Investigation queue',exceptions(),tag(state.alerts.length+' open','warning'))}</div>${panel('PAPER / SHADOW','Reconciliation evidence',state.execution.runtimes.length?table('reconciliation',[['runtime_id','Runtime',r=>inspect(r.runtime_id,r.runtime_id)],['last_reconcile_at','Last reconciliation',r=>stamp(r.last_reconcile_at)],['status','Status',r=>tag(r.status)],['halt_reason','Halt reason']],state.execution.runtimes):empty('Reconciliation unavailable','Infrastructure acceptance tests are not proof of the current account reconciliation.','runtime-source'))}`;}
function jobs(){return `<div class="wide-panel">${flow()}</div><div class="wide-panel">${panel('F5.6 / PERSISTED RUNTIMES','Runtime observations',intro('A persisted RUNNING label can be stale. Check heartbeat and lease. Task start times, elapsed task durations, named agents and schedules are not supplied by this backend.')+(state.execution.runtimes.length?table('runtimes',[['runtime_id','Runtime',r=>inspect(r.runtime_id,r.runtime_id)],['mode','Mode'],['status','Persisted status',r=>tag(r.status)],['freshness','Heartbeat freshness',r=>tag(r.freshness)],['last_heartbeat_at','Last heartbeat',r=>stamp(r.last_heartbeat_at)],['lease_state','Lease',r=>tag(r.lease_state)],['event_count','Events'],['created_at','Record created',r=>stamp(r.created_at)]],state.execution.runtimes,{search:true,filter:{key:'status',label:'states'}}):empty('No runtime records connected','Worker and schedule telemetry is unavailable.','jobs-source')),inspect('jobs-source','Telemetry scope ↗'))}</div>${panel('LAST 100 OBSERVED EVENTS','Activity stream',activity(),tag('SOURCE TIMESTAMPS','cyan'))}`;}
function evidence(){const rows=Object.entries(state.market.records).map(([id,r])=>({id,path:r.path,sha256:r.sha256||'Not supplied',classification:r.classification||'ARCHIVAL EVIDENCE'}));return `<div class="wide-panel">${panel('SOURCE REGISTER','Evidence & provenance',table('evidence',[['id','Record',r=>inspect(r.id,r.id)],['classification','Classification'],['path','Source path'],['sha256','SHA-256',r=>`<code>${esc(r.sha256.slice(0,20))}${r.sha256.length>20?'…':''}</code>`]],rows,{search:true}),tag(rows.length+' records','cyan'))}</div><div class="grid equal">${panel('OBSERVER','Connection diagnostics',`<div class="panel-body">${kv({status:connection,environment:state.meta.environment,schema:state.schema_version,source:state.meta.source,api_response_at:lastReceived,market_source_time:state.market.manifest.decision_time||'Unavailable',runtime_db:state.meta.runtime_connected?'Readable':'Not connected',fixtures:state.meta.fixtures?'DEMO / TEST ONLY':'None'})}</div>`,inspect('diagnostics','Inspect ↗'))}${panel('AUTHORITY BOUNDARY','Observation without execution',`<div class="panel-body">${kv({database:'Read-only / query-only',lease_mutations:'None',broker_submission:'Not exposed',live_enablement:'Not exposed',risk_limit_changes:'Not exposed',alpha_v1_and_f7:'Unchanged',promotion:'Separate production commissioning required'})}</div>`,tag('READ ONLY','cyan'))}</div>`;}
function render(){if(!state)return;const scrolls=[...document.querySelectorAll('.table-wrap')].map(e=>[e.scrollLeft,e.scrollTop]);renderedSignature=signature(state);setupInvestigations();$('#title').textContent=titles[page][0];$('#breadcrumb').textContent=titles[page][1].toUpperCase();$('#workspace').innerHTML=({overview,data:dataPage,research,strategies,runtime,risk,jobs,evidence,...(typeof portfolio==='function'?{portfolio,readiness}:{})}[page])();$('#nav').innerHTML=Object.entries(titles).map(([key,[,label,icon]])=>`<a href="#${key}" title="${label}" aria-label="${label}" ${page===key?'aria-current="page"':''} class="nav-link ${page===key?'active':''}"><b aria-hidden="true">${icon}</b><span>${label}</span></a>`).join('');updateSourceBanner();$('#environment').textContent=state.meta.environment;$('#mode-label').textContent=state.meta.mode;document.querySelectorAll('.table-wrap').forEach((e,i)=>{if(scrolls[i]){e.scrollLeft=scrolls[i][0];e.scrollTop=scrolls[i][1];}});}
function updateSourceBanner(){$('#source-banner').innerHTML=`<span><strong>${state.meta.fixtures?'DEMO / TEST DATA':state.meta.source}</strong> · ${state.meta.runtime_connected?'Runtime observations connected':'Runtime disconnected'} · ${state.health==='CRITICAL'?'CRITICAL EXCEPTIONS':state.health} · ${state.execution.runtimes.length?'Heartbeat: '+state.execution.runtimes.map(r=>r.freshness).filter((v,i,a)=>a.indexOf(v)===i).join(' / '):'Heartbeat unavailable'}</span><span class="secondary">Market evidence: 22 SEP 2026 · Not a live feed</span>`;}
function navigate(key){if(!titles[key])key='overview';page=key;location.hash=key;render();}
function openDrawer(id){const item=investigations.get(id);if(!item)return;currentDrawer=id;$('#drawer-title').textContent=item.title;$('#drawer-body').innerHTML=`<div class="drawer-section"><span class="tag cyan">READ-ONLY INSPECTION</span></div>${item.body}`;if(!$('#drawer').open)$('#drawer').showModal();}
function notify(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2500);}
function palette(){const q=$('#command-search').value.toLowerCase();const results=Object.entries(titles).map(([id,[,label]])=>({id,label,type:'Workspace'})).concat([{id:'runtime-source',label:'Inspect runtime connection',type:'Evidence'},{id:'performance',label:'Inspect equity / performance source',type:'Evidence'},{id:'data-source',label:'Investigate stale market data',type:'Evidence'},{id:'risk-source',label:'Inspect risk authority',type:'Evidence'}]).filter(x=>x.label.toLowerCase().includes(q));$('#commands').innerHTML=results.map(x=>`<button class="command" ${x.type==='Workspace'?`data-go="${x.id}"`:`data-inspect="${x.id}"`}><span>${esc(x.label)}</span><small>${x.type} ↵</small></button>`).join('')||intro('No matching commands.');}
function openPalette(){palette();$('#palette').showModal();$('#command-search').focus();}
async function refresh(){if(fetching)return;fetching=true;$('#refresh').disabled=true;try{const response=savedSnapshot?{ok:true,json:async()=>savedSnapshot}:await fetch('/api/dashboard',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('HTTP '+response.status);const payload=await response.json();if(payload.schema_version!=='eqs-operator-v3'||payload.meta?.mutations_enabled!==false||!payload.market||!Array.isArray(payload.alerts))throw Error('Incompatible observer response');const changed=signature(payload)!==renderedSignature;state=payload;connection=savedSnapshot?'Saved preview · not connected':'Observer connected';lastReceived=savedSnapshot?state.meta.generated_at:new Date().toISOString();$('#failure').hidden=true;$('#connection').textContent=connection;$('#fetched').textContent=(savedSnapshot?'Saved snapshot ':'API response ')+shortTime(lastReceived)+' UTC · Upstream time unchanged';$('#source-banner').dataset.health=state.health;updateSourceBanner();if(changed&&!$('#drawer').open&&!$('#palette').open&&!$('#workspace').contains(document.activeElement))render();}catch(error){connection='Observer disconnected';$('#connection').textContent=connection;$('#failure').hidden=false;$('#failure').textContent=`Connection failed (${error.message}). ${state?'Last-known values retained; last response '+stamp(lastReceived)+'.':'No source values available.'}`;}finally{fetching=false;$('#refresh').disabled=false;}}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.close){$('#'+b.dataset.close).close();return;}if(b.dataset.go){$('#drawer').close();$('#palette').close();navigate(b.dataset.go);return;}if(b.dataset.inspect){$('#palette').close();openDrawer(b.dataset.inspect);return;}if(b.dataset.mode){view.mode=b.dataset.mode;render();return;}if(b.dataset.sort){const id=b.dataset.sort,key=b.dataset.key;view.sort[id]={key,dir:view.sort[id]?.key===key?-view.sort[id].dir:1};render();return;}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='chart-type'){view.chart=t.value;render();}if(t.id==='chart-venue'){view.venue=t.value;view.point=0;render();}if(t.id==='chart-range'){view.range=t.value;view.point=0;render();}if(t.dataset.filter){view.filter[t.dataset.filter]=t.value;render();}if(t.id==='density'){document.body.classList.toggle('compact',t.value==='compact');try{localStorage.setItem('eqs-density',t.value);}catch{}}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.search){const id=t.dataset.search,start=t.selectionStart;view.search[id]=t.value;render();const input=$(`[data-search="${id}"]`);input.focus();input.setSelectionRange(start,start);}if(t.id==='chart-point'){view.point=Number(t.value);render();$('#chart-point')?.focus();}});
$('#command-search').addEventListener('input',palette);$('#palette-open').addEventListener('click',openPalette);$('#refresh').addEventListener('click',refresh);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#palette').open?$('#palette').close():openPalette();}if(e.key==='Enter'&&e.target.id==='command-search'){e.preventDefault();$('#commands button')?.click();}if(e.key.toLowerCase()==='r'&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)&&!$('#drawer').open&&!$('#palette').open){e.preventDefault();refresh();}});
window.addEventListener('hashchange',()=>{page=titles[location.hash.slice(1)]?location.hash.slice(1):'overview';render();});
try{const density=localStorage.getItem('eqs-density');if(density==='compact'){$('#density').value=density;document.body.classList.add('compact');}}catch{}
page=titles[location.hash.slice(1)]?location.hash.slice(1):'overview';$('#nav').innerHTML=Object.entries(titles).map(([key,[,label,icon]])=>`<a href="#${key}" class="nav-link" aria-label="${label}"><b>${icon}</b><span>${label}</span></a>`).join('');
$('#clock').textContent=new Date().toISOString().slice(11,19)+' UTC';
setInterval(()=>{$('#clock').textContent=new Date().toISOString().slice(11,19)+' UTC';},1000);
setInterval(()=>{if(!document.hidden&&!savedSnapshot)refresh();},15000);refresh();
