/* Market-led review workspace. Public prices never confer execution authority. */
const embeddedMarkets=document.getElementById('saved-markets');
let marketFeed=embeddedMarkets?JSON.parse(embeddedMarkets.textContent):null,marketBusy=false,marketFailure=null;
const trading={symbol:'BTCUSDT',venue:'BYBIT_LINEAR',interval:'1m',bars:70,point:null,style:'candles',ema:false,tab:'positions'};
const oldOverview=overview;
titles.overview=['Trading overview','Trading overview','◫'];
const marketPrice=(n)=>number(n,2);
const tickTime=ms=>ms?new Date(ms).toISOString().slice(11,19)+' UTC':'Unknown source time';
const direction=n=>n>=0?'up':'down';
function visibleCandles(){return (marketFeed?.symbol===trading.symbol&&marketFeed?.interval===trading.interval?marketFeed.candles:[]).slice(-trading.bars);}
function componentState(name){
 if(embeddedMarkets)return 'SAVED';
 if(!marketFeed)return 'CONNECTING';
 if(marketFailure)return 'DISCONNECTED';
 const part=marketFeed.components?.[name];
 if(part&&part.state!=='LIVE')return part.state;
 const stamp=name==='candles'?marketFeed.candles?.at(-1)?.time:name==='book'?marketFeed.book?.time:name==='mark'?marketFeed.mark?.time:marketFeed.tickers?.find(t=>t.symbol===name)?.time;
 const age=(Date.now()-stamp)/1000,limit=name==='candles'?({'1m':60,'5m':300,'15m':900,'1h':3600}[trading.interval]+30):30;
 return !Number.isFinite(age)?'UNAVAILABLE':age < -5?'CLOCK SKEW':age>limit?'STALE':'LIVE';
}
function marketIsFresh(){return !embeddedMarkets&&marketFeed?.symbol===trading.symbol&&marketFeed?.interval===trading.interval&&['candles','book','mark',trading.symbol].every(k=>componentState(k)==='LIVE')&&!marketFailure;}
function marketLabel(){return embeddedMarkets?'SAVED MARKET CAPTURE':marketFailure?'DISCONNECTED / LAST KNOWN':!marketFeed?'CONNECTING':marketFeed.symbol!==trading.symbol||marketFeed.interval!==trading.interval?'LOADING SELECTED MARKET':marketIsFresh()?'LIVE · 10s POLL':'PARTIAL / STALE DATA';}
function marketEvidence(){register('public-market','Public market observation',intro('Binance USDⓈ-M futures public market data. Observational only; not an order route. Candles are trade-price OHLC; the last candle may be forming. The mark price is shown separately. Order book is a bounded snapshot, not a gap-audited L2 history.')+kv({source:marketFeed?.source,symbol:trading.symbol,interval:trading.interval,state:marketLabel(),source_time:tickTime(marketFeed?.mark?.time),fetched_at:marketFeed?.fetched_at,quote_currency:'USDT',refresh:'10-second polling, last-known values on failure',errors:marketFeed?.errors||marketFailure})+json({mark:marketFeed?.mark,book_time:marketFeed?.book?.time,book_sequence:marketFeed?.book?.sequence}));}
function watchlist(){return `<div class="market-watch">${['BYBIT_LINEAR','OKX_SWAP'].map(venue=>{const symbol=venue==='BYBIT_LINEAR'?'BTCUSDT':'BTC-USDT-SWAP',q=marketFeed?.venue===venue?marketFeed?.tickers?.[0]:null;return `<button class="watch-item ${venue===trading.venue?'selected':''}" data-market-venue="${venue}" ><div><strong>${symbol.replace('USDT',' / USDT')}</strong><small>${venue==='BYBIT_LINEAR'?'BYBIT':'OKX'} · ${marketFeed?.venue===venue?componentState(symbol):'SELECT TO LOAD'}</small></div><div class="watch-price"><b>${q?marketPrice(q.price):'—'}</b><span class="${direction(q?.change_pct||0)}">${q?(q.change_pct>=0?'+':'')+number(q.change_pct)+'%':'Unavailable'} <small>24h</small></span></div></button>`;}).join('')}</div>`;}
function candleChart(){const rows=visibleCandles();const controls=`<div class="trading-toolbar"><div class="timeframes">${['1m','5m','15m','1h'].map(t=>`<button data-timeframe="${t}" aria-pressed="${trading.interval===t}">${t}</button>`).join('')}</div><label>Range <select id="trading-bars"><option value="40" ${trading.bars===40?'selected':''}>40 candles</option><option value="70" ${trading.bars===70?'selected':''}>70 candles</option><option value="100" ${trading.bars===100?'selected':''}>100 candles</option></select></label><button data-chart-style aria-label="Switch chart style">${trading.style==='candles'?'Line':'Candles'}</button><button data-ema aria-pressed="${trading.ema}">EMA 20</button><button data-expand aria-label="Expand chart">Expand</button></div>`;
 if(!rows.length)return controls+empty('Waiting for public market candles',marketFailure||'The review server requests current Binance futures prices. No demonstration candles are substituted.','public-market');
 const width=window.innerWidth<600?Math.max(310,window.innerWidth-65):1100,height=365,left=12,right=width-85,top=24,bottom=260,step=(right-left)/rows.length;
 const lo=Math.min(...rows.map(r=>r.low)),hi=Math.max(...rows.map(r=>r.high)),padding=Math.max((hi-lo)*.08,.01),min=lo-padding,max=hi+padding;
 const y=p=>bottom-(p-min)/(max-min)*(bottom-top),maxVol=Math.max(...rows.map(r=>r.volume),1),index=Math.max(0,Math.min(trading.point??rows.length-1,rows.length-1)),selected=rows[index];
 register('selected-candle','Candle · '+new Date(selected.time).toISOString(),intro('Observed public trade-price candle. Current interval may be incomplete. Volume is base-asset quantity.')+json(selected)+inspect('public-market','Feed provenance →'));
 const all=marketFeed.candles;let ema=all[0].close;const emaPoints=all.map((r,i)=>{ema=i?ema+(r.close-ema)*2/21:ema;return ema;}).slice(-rows.length);
 const labels=window.innerWidth<600?[0,rows.length-1]:[0,Math.floor(rows.length/3),Math.floor(rows.length*2/3),rows.length-1];
 return controls+`<div class="ohlc-line"><span>${tickTime(selected.time)}</span><span>O <b>${marketPrice(selected.open)}</b></span><span>H <b>${marketPrice(selected.high)}</b></span><span>L <b>${marketPrice(selected.low)}</b></span><span>C <b class="${direction(selected.close-selected.open)}">${marketPrice(selected.close)}</b></span><span>Vol <b>${number(selected.volume,3)}</b></span></div><svg class="candlestick-chart ${trading.style==='line'?'line-style':''}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(rows.length+' Binance '+trading.symbol+' '+trading.interval+' candlesticks; low '+lo+' high '+hi+' USDT; volume below')}" preserveAspectRatio="none">${[0,.25,.5,.75,1].map(v=>{const p=min+(max-min)*v;return `<line x1="${left}" x2="${right}" y1="${y(p)}" y2="${y(p)}" class="chart-grid"/><text x="${right+8}" y="${y(p)+4}">${marketPrice(p)}</text>`;}).join('')}${rows.map((r,i)=>{const xx=left+i*step+step/2,up=r.close>=r.open,c=up?'#62c7a5':'#ef7b88',vh=r.volume/maxVol*49;return `<line x1="${xx}" x2="${xx}" y1="${y(r.high)}" y2="${y(r.low)}" stroke="${c}" class="candle-body"/><rect x="${xx-step*.32}" y="${Math.min(y(r.open),y(r.close))}" width="${Math.max(step*.64,.8)}" height="${Math.max(Math.abs(y(r.open)-y(r.close)),1.2)}" fill="${c}" class="candle-body"/><rect x="${xx-step*.32}" y="${330-vh}" width="${Math.max(step*.64,.8)}" height="${vh}" fill="${c}" opacity=".38"/>`;}).join('')}${trading.style==='line'?`<polyline points="${rows.map((r,i)=>`${left+i*step+step/2},${y(r.close)}`).join(' ')}" fill="none" stroke="#69c7e8" stroke-width="2"/>`:''}${trading.ema?`<polyline points="${emaPoints.map((v,i)=>`${left+i*step+step/2},${y(v)}`).join(' ')}" fill="none" stroke="#d7b474" stroke-width="1.7"/>`:''}<line x1="${left}" x2="${right}" y1="${y(rows.at(-1).close)}" y2="${y(rows.at(-1).close)}" stroke="#69c7e8" stroke-dasharray="4 5" opacity=".6"/><line x1="${left+index*step+step/2}" x2="${left+index*step+step/2}" y1="${top}" y2="330" stroke="#93acc5" stroke-dasharray="2 5" opacity=".6"/><text x="${left}" y="282">VOLUME</text>${labels.map(i=>`<text x="${Math.min(right-65,left+i*step)}" y="354">${new Date(rows[i].time).toISOString().slice(11,16)}</text>`).join('')}</svg><div class="candle-inspection"><label>Inspect candle <input type="range" id="candle-index" min="0" max="${rows.length-1}" value="${index}" aria-label="Inspect candle"></label>${inspect('selected-candle','Candle details ↗')}</div>`;
}
function bookPanel(){const b=marketFeed?.symbol===trading.symbol?marketFeed.book:null;
 if(!b?.bids?.length||!b?.asks?.length)return panel('PUBLIC MARKET','Order book',empty('Depth unavailable','Waiting for a valid public order-book snapshot.','public-market'),tag('UNAVAILABLE','warning'));
 const bids=b.bids.slice(0,8),asks=b.asks.slice(0,8).reverse(),max=Math.max(...[...bids,...asks].map(r=>r[1]),1),spread=b.asks[0][0]-b.bids[0][0];
 return panel('20 LEVELS · '+componentState('book'),'Order book',`<div class="book-labels"><span>Price / USDT</span><span>Quantity / ${trading.symbol.replace('USDT','')}</span></div>${asks.map(r=>`<div class="book-row ask" style="--depth:${r[1]/max*100}%"><span>${marketPrice(r[0])}</span><span>${number(r[1],3)}</span></div>`).join('')}<div class="spread-line"><strong>${marketPrice(marketFeed.mark?.price)}</strong><span>Mark · spread ${marketPrice(spread)}</span></div>${bids.map(r=>`<div class="book-row bid" style="--depth:${r[1]/max*100}%"><span>${marketPrice(r[0])}</span><span>${number(r[1],3)}</span></div>`).join('')}<div class="panel-foot">${tickTime(b.time)} · top 8 levels shown</div>`,inspect('public-market','↗'));
}
function depthChart(){const b=marketFeed?.symbol===trading.symbol?marketFeed.book:null;if(!b?.bids?.length||!b?.asks?.length)return empty('Depth profile unavailable','No order-book snapshot received.','public-market');
 const bid=b.bids.map(([p,q])=>[p,q]),ask=b.asks.map(([p,q])=>[p,q]);let bq=0,aq=0;const bids=bid.map(([p,q])=>[p,bq+=q]).reverse(),asks=ask.map(([p,q])=>[p,aq+=q]);const min=bids[0][0],max=asks.at(-1)[0],height=Math.max(bq,aq),x=p=>20+(p-min)/Math.max(max-min,.01)*500,y=q=>115-q/height*90;
 return `<svg class="depth-chart" viewBox="0 0 550 145" role="img" aria-label="Cumulative 20-level bids and asks in ${trading.symbol.replace('USDT','')}">${[[bids,'#62c7a5'],[asks,'#ef7b88']].map(([rows,c])=>`<polygon points="${x(rows[0][0])},115 ${rows.map(([p,q])=>`${x(p)},${y(q)}`).join(' ')} ${x(rows.at(-1)[0])},115" fill="${c}" opacity=".12"/><polyline points="${rows.map(([p,q])=>`${x(p)},${y(q)}`).join(' ')}" fill="none" stroke="${c}" stroke-width="2"/>`).join('')}<text x="20" y="137">${marketPrice(min)}</text><text x="450" y="137">${marketPrice(max)}</text></svg><div class="depth-values"><span class="up">Bids ${number(bq,3)}</span><span class="down">Asks ${number(aq,3)}</span><small>Cumulative base quantity · 20 levels</small></div>`;
}
function venuePaper(){return state.execution.paper_by_venue?.[trading.venue]||state.execution.paper||{}}
function valuationChart(){const p=venuePaper(),rows=p.valuation_history||[];if(!rows.length)return empty('Valuation history unavailable','Waiting for persisted PAPER valuation snapshots.','performance');const w=760,h=190,l=15,r=w-70,t=15,b=155;const eq=rows.map(x=>Number(x.equity)),pn=rows.map(x=>Number(x.unrealized_pnl)),mk=rows.map(x=>Number(Object.values(x.marks||{})[0]));const series=view.chart==='pnl'?pn:view.chart==='mark'?mk:eq;const lo=Math.min(...series),hi=Math.max(...series),pad=Math.max((hi-lo)*.15,Math.abs(hi||1)*.00001,.01),mn=lo-pad,mx=hi+pad,x=i=>l+i/Math.max(rows.length-1,1)*(r-l),y=v=>b-(v-mn)/Math.max(mx-mn,.000001)*(b-t);const label=view.chart==='pnl'?'Unrealised P&L':view.chart==='mark'?'Venue mark':'PAPER equity';return `<div class="chart-controls"><button data-valuation-chart="equity">Equity</button><button data-valuation-chart="pnl">Unrealised P&L</button><button data-valuation-chart="mark">Mark</button></div><svg class="chart" viewBox="0 0 ${w} ${h}"><polyline points="${series.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#69c7e8" stroke-width="2"/><text x="${l}" y="180">${shortTime(rows[0].observed_at)}</text><text x="${r-75}" y="180">${shortTime(rows.at(-1).observed_at)}</text></svg><div class="chart-inspect">${esc(label)} � ${rows.length} persisted observations � latest ${number(series.at(-1),4)}</div>`;}
function valuationPanel(){return panel('PAPER / PERSISTED VALUATIONS','Account time series',valuationChart(),tag('LIVE VALUATION','good'),'<span>Genuine venue marks � persisted runtime history</span>');}
function fillsPanel(){const p=venuePaper(),rows=p.fills||[];return panel('PAPER / SIMULATED EXECUTION','Recent fills',rows.length?table('paper-fills',[['id','Fill'],['order_id','Order'],['price','Price',r=>number(r.price,4)],['qty','Qty',r=>number(r.qty,6)],['fee','Fee',r=>number(r.fee,6)],['timestamp','Time',r=>shortTime(r.timestamp)]],rows.slice(-50).reverse()):empty('No PAPER fills','No simulated executions are persisted in the selected PAPER runtime.','runtime-source'),tag(String(rows.length)+' fills','cyan'));}
function positionsPanel(){const p=venuePaper(),rows=(p.positions||[]).filter(r=>Number(r.qty)!==0);
 register('position-pricing','Open positions & live P&L',intro('To value an open position, EQS needs its quantity, entry price, exact venue/instrument, contract multiplier and settlement currency, plus a fresh matching mark. This F5.6 checkpoint does not persist all of those fields. A generic Binance quote must not be silently applied to another venue or contract.')+json({runtime:p.runtime_id,source:state.execution.source,positions:rows}));
 return panel('PAPER / LATEST PERSISTED RUNTIME','Open trades',`<div class="positions-tabs"><strong>Positions ${p.available?'('+rows.length+')':'(unavailable)'}</strong><button class="link-button" data-go="runtime">Orders & fills →</button><span class="tag cyan">PAPER · SIMULATED EXECUTION</span></div>`+(rows.length?table('open-trades',[['symbol','Market'],['side','Side'],['qty','Size'],['avg_price','Entry'],['mark','Live mark',r=>number(r.mark,4)],['realized_pnl','Realised P&L',r=>number(r.realized_pnl,4)],['pnl','Unrealised P&L',r=>number(r.pnl,4)],['inspection','Inspect',r=>inspect('position-pricing')]],rows):`<div class="table-wrap"><table><thead><tr><th>Market</th><th>Side</th><th>Size</th><th>Entry</th><th>Live mark</th><th>Unrealised P&L</th></tr></thead></table></div><div class="positions-empty"><strong>${p.available?'No open positions in this checkpoint':'Runtime not connected'}</strong><p>${p.available?'The connected PAPER ledger has no nonzero positions.':'Real market prices are independent of trading activity. Connect the EQS runtime to populate open trades, cash and realised P&L.'}</p>${inspect('runtime-source','Runtime connection →')}</div>`),inspect('position-pricing','P&L definition ↗'));
}
overview=function(){marketEvidence();const p=venuePaper(),q=marketFeed?.tickers?.find(t=>t.symbol===trading.symbol);
 return watchlist()+`<div class="trading-summary"><div><span>ACCOUNT / PAPER</span><b>${esc(p.runtime_id||'Not connected')}</b></div><button data-inspect="cash"><span>Cash</span><b>${number(p.cash)}</b></button><button data-inspect="pnl"><span>Realised P&L</span><b>${number(p.realized_pnl)}</b></button><button data-inspect="position-pricing"><span>Unrealised P&L</span><b>${p.unrealized_pnl==null?'—':number(p.unrealized_pnl,4)}</b></button><button data-inspect="performance"><span>PAPER equity</span><b>${p.equity==null?'—':number(p.equity,4)}</b></button><button data-inspect="alert-0"><span>Exceptions</span><b class="warning-text">${state.alerts.length} to inspect ↗</b></button></div><div class="trading-grid">${panel((trading.venue==='BYBIT_LINEAR'?'BYBIT LINEAR':'OKX SWAP')+' · USDT',trading.symbol.replace('USDT',' / USDT'),candleChart(),`<div class="chart-heading-quote"><strong>${q?marketPrice(q.price):'—'}</strong><span class="${direction(q?.change_pct||0)}">${q?(q.change_pct>=0?'+':'')+number(q.change_pct)+'% · 24h':''}</span></div>`,`<span>${marketLabel()} · ${tickTime(q?.time)} · forming candle included</span>${tag(embeddedMarkets?'SAVED':marketIsFresh()?'LIVE':'ATTENTION',marketIsFresh()?'good':'warning')}`)}${bookPanel()}</div><div class="positions-grid">${positionsPanel()}${panel('LIQUIDITY / '+trading.symbol,'Market depth',depthChart(),inspect('public-market','Source ↗'))}</div><div class="positions-grid">${valuationPanel()}${fillsPanel()}</div><div class="terminal-foot"><span>MARKET FEED ${marketLabel()} · ACCOUNT ${p.available?'PAPER CHECKPOINT':'DISCONNECTED'}</span><button class="link-button" data-go="risk">Risk & exceptions →</button><button class="link-button" data-go="research">Research & strategy eligibility →</button></div>`;
};
const previousBanner=updateSourceBanner;updateSourceBanner=function(){previousBanner();if(page==='overview'){const secondary=$('#source-banner .secondary');if(secondary)secondary.textContent='MARKETS '+marketLabel()+' · NO LIVE TRADING AUTHORITY';}};
function renderTrading(force=false){if(state&&page==='overview'&&!$('#drawer').open&&!$('#palette').open){const focus=document.activeElement?.id;if(!force&&$('#workspace').contains(document.activeElement)&&focus!=='candle-index')return;render();if(focus==='candle-index')$('#candle-index')?.focus();}else if(state)updateSourceBanner();}
async function refreshMarkets(){
 if(marketBusy||embeddedMarkets)return;
 marketBusy=true;const symbol=trading.symbol,interval=trading.interval;
 try{
  const r=await fetch('/api/markets?venue='+trading.venue+'&symbol='+symbol+'&interval='+interval,{cache:'no-store',signal:AbortSignal.timeout(9000)});
  if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();
  if(symbol!==trading.symbol||interval!==trading.interval)return;
  if(data.symbol!==symbol||data.interval!==interval||data.venue!==trading.venue||data.read_only!==true||!Array.isArray(data.candles))throw Error('Incompatible market feed');
  marketFeed=data;marketFailure=null;renderTrading();
 }catch(e){if(symbol===trading.symbol&&interval===trading.interval){marketFailure=e.message;renderTrading();}}
 finally{marketBusy=false;if(symbol!==trading.symbol||interval!==trading.interval)refreshMarkets();}
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.marketVenue){trading.venue=b.dataset.marketVenue;trading.symbol=trading.venue==='BYBIT_LINEAR'?'BTCUSDT':'BTC-USDT-SWAP';trading.point=null;marketFeed=null;renderTrading(true);refreshMarkets();}if(b?.dataset.marketSymbol){if(embeddedMarkets&&embeddedMarkets.dataset.scope==='single'){notify('Saved preview contains '+trading.symbol+' only. Use the running server for other markets.');return;}trading.symbol=b.dataset.marketSymbol;trading.point=null;renderTrading(true);refreshMarkets();}if(b?.dataset.timeframe){if(embeddedMarkets){notify('Saved capture only. Timeframe changes need the running market connection.');return;}trading.interval=b.dataset.timeframe;trading.point=null;renderTrading(true);refreshMarkets();}});
document.addEventListener('change',e=>{if(e.target.id==='trading-bars'){trading.bars=Number(e.target.value);trading.point=null;renderTrading(true);}});
document.addEventListener('input',e=>{if(e.target.id==='candle-index'){trading.point=Number(e.target.value);renderTrading(true);}});
$('#refresh').addEventListener('click',refreshMarkets);setInterval(()=>{if(!document.hidden&&!$('#drawer').open&&!$('#palette').open)refreshMarkets();},10000);
if(embeddedMarkets){trading.symbol=marketFeed.symbol;trading.interval=marketFeed.interval;}else refreshMarkets();

if(state)renderTrading();

document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.valuationChart){view.chart=b.dataset.valuationChart;renderTrading(true);}});
