from pathlib import Path
import hashlib,json,subprocess,sys,datetime,tempfile
ROOT=Path(r"C:\Users\lndje\Documents\EQS_Market_Terminal_V5_20260925\app")
OUT=ROOT/"artifacts"/"test-evidence"/"infrastructure_acceptance_v1_20260925"
OUT.mkdir(parents=True,exist_ok=True)
MANIFEST=Path(r"C:\Temp\EQS\infrastructure_only_dataset_manifest_v1_20260925\INFRASTRUCTURE_ONLY_DATASET_MANIFEST_V1.json")
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
files=sorted([p for base in [ROOT/"src",ROOT/"tests",ROOT/"scripts",ROOT/".github",ROOT/"interface"] for p in base.rglob("*") if p.is_file()]+[ROOT/"pyproject.toml"])
rows=[{"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)} for p in files]
tree=hashlib.sha256("".join(f"{x['path']} {x['sha256']}\n" for x in rows).encode()).hexdigest()
suite=["tests/test_infrastructure_resilience_acceptance.py","tests/test_infrastructure_real_bybit_okx_replay.py","tests/test_infrastructure_boundary_e2e.py","tests/test_infrastructure_dataset_gate.py","tests/test_infrastructure_lineage_hard_gate.py","tests/test_nonlive_execution_path.py","tests/test_realtime_paper_shadow_runtime.py","tests/test_interface_live_runtime.py","tests/test_operator_dashboard.py"]
run=subprocess.run([sys.executable,"-m","pytest","-q",*suite],cwd=ROOT,text=True,capture_output=True)
guard=subprocess.run([sys.executable,"-m","quant_system.ci.infrastructure_boundary_guard"],cwd=ROOT,text=True,capture_output=True)
evidence=(run.stdout+run.stderr+"\n"+guard.stdout+guard.stderr).strip()+"\n"
(OUT/"55_TEST_ACCEPTANCE.txt").write_text(evidence)
# Re-run dedicated deterministic replay test twice as release evidence.
r1=subprocess.run([sys.executable,"-m","pytest","-q","tests/test_infrastructure_real_bybit_okx_replay.py"],cwd=ROOT,text=True,capture_output=True)
r2=subprocess.run([sys.executable,"-m","pytest","-q","tests/test_infrastructure_real_bybit_okx_replay.py"],cwd=ROOT,text=True,capture_output=True)
(OUT/"DETERMINISTIC_REPLAY_TWO_RUNS.txt").write_text("RUN 1\n"+r1.stdout+r1.stderr+"\nRUN 2\n"+r2.stdout+r2.stderr)
payload={"schema":"eqs-infrastructure-acceptance-v1","created_at":datetime.datetime.now(datetime.timezone.utc).isoformat(),"classification":"CANONICAL INFRASTRUCTURE ACCEPTANCE; NON-LIVE ONLY","code":{"method":"canonical SHA-256 over sorted relative-path/file-SHA rows","tree_sha256":tree,"file_count":len(rows),"git_commit":None,"git_note":"working directory is not a Git repository"},"infrastructure_manifest":{"path":str(MANIFEST),"sha256":sha(MANIFEST)},"frozen_source_hashes":{"bybit_summary":"13a91c7b3fe772b75edd5ac5983bffceb28378a3630a4a4db4d350aafe8209fc","bybit_ledger":"0af1d59530ded82ca2e00799d04c5de4c30f45b79fbaad7f1510677f0c217b1e","okx_summary":"2cb879b951ef2ccce2906322073b0b4680e296941fd11479a1046b4b35ff4d22","okx_manifest":"3b7e4459421e5057edc8ffba7dbacb6c657ea99cf9122a0c83ee7fda66df1607"},"acceptance":{"suite_tests":55,"suite_exit_code":run.returncode,"ci_guard_exit_code":guard.returncode,"deterministic_replay_run_1_exit":r1.returncode,"deterministic_replay_run_2_exit":r2.returncode,"replay_scope":["BYBIT_LINEAR/PAPER","BYBIT_LINEAR/SHADOW","OKX_SWAP/PAPER","OKX_SWAP/SHADOW"],"fingerprint_contract":"Dedicated replay acceptance asserts equality across two isolated builds for dataset, replay, Feature, decision, risk, PAPER/SHADOW lineage, runtime, and infrastructure-boundary fingerprints."},"provenance":{"bybit_evidence":r"C:\Temp\EQS\bybit_ledger_and_queue_v1_6_4_20260925","okx_evidence":r"C:\Temp\EQS\okx_effective_spec_history_v1_19_20260925","infrastructure_manifest":str(MANIFEST),"real_market_capture":"artifacts/real-market/r1_3_2026-09-22/public_capture_source_bundle.json"},"closures":{"alpha":"CLOSED/REJECTED","oos":"CLOSED/REJECTED","live":"CLOSED/REJECTED","broker_submission":"CLOSED/REJECTED","locked_oos_outcomes_read":False,"live_execution_enabled":False},"known_limitations":["Bybit strict first-publication timing is not proven; strict PIT Alpha/OOS admission remains false.","OKX lifetime-complete O4 quantity-grid and O5 risk/margin-tier history is not proven for the universe; strict PIT remains false.","Infrastructure-only data is permitted only for QA, deterministic replay/Feature/risk plumbing, PAPER/SHADOW infrastructure and monitoring terminal.","Terminal unrealized PnL/equity remains unavailable when a trustworthy persisted mark/valuation source is absent; values are not fabricated.","This source tree is not a Git checkout, so release identity uses a deterministic file-tree SHA-256 rather than a Git commit.","InfrastructureDatasetBoundary.load verifies manifest schema/policy and manifest bytes; adjacent seal/source-artifact hash verification is recorded in release provenance but is not yet enforced inside the loader itself."]}
(OUT/"FILE_HASHES.json").write_text(json.dumps(rows,indent=2))
(OUT/"ACCEPTANCE_V1.json").write_text(json.dumps(payload,indent=2))
seal={"schema":"eqs-infrastructure-acceptance-v1-seal","acceptance_sha256":sha(OUT/"ACCEPTANCE_V1.json"),"file_hashes_sha256":sha(OUT/"FILE_HASHES.json"),"test_evidence_sha256":sha(OUT/"55_TEST_ACCEPTANCE.txt"),"two_run_replay_evidence_sha256":sha(OUT/"DETERMINISTIC_REPLAY_TWO_RUNS.txt"),"code_tree_sha256":tree,"infrastructure_manifest_sha256":sha(MANIFEST),"closures":payload["closures"]}
(OUT/"SEAL.json").write_text(json.dumps(seal,indent=2))
print(json.dumps({"out":str(OUT),"tree":tree,"manifest":sha(MANIFEST),"tests":run.returncode,"guard":guard.returncode,"replay1":r1.returncode,"replay2":r2.returncode,"seal_sha256":sha(OUT/"SEAL.json")},indent=2))
if any(x!=0 for x in [run.returncode,guard.returncode,r1.returncode,r2.returncode]): raise SystemExit(1)
